// Objective-C API for talking to greeting Go package.
//   gobind -lang=objc greeting
//
// File is generated by gobind. Do not edit.

#ifndef __Greeting_H__
#define __Greeting_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull GreetingSayHi(NSString* _Nullable text);

#endif
