
// Objective-C API for talking to the following Go packages
//
//	greeting
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Greeting_FRAMEWORK_H__
#define __Greeting_FRAMEWORK_H__

#include "Greeting.objc.h"
#include "Universe.objc.h"

#endif
