
// Objective-C API for talking to the following Go packages
//
//	git.woa.com/noc-dev/itango/itangosdk
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Itangosdk_FRAMEWORK_H__
#define __Itangosdk_FRAMEWORK_H__

#include "Itangosdk.objc.h"
#include "Universe.objc.h"

#endif
